In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df_x = pd.read_csv("./Training/Logistic_X_Train.csv")
df_y = pd.read_csv("./Training/Logistic_Y_Train.csv")

In [3]:
df_x.head

<bound method NDFrame.head of             f1        f2        f3
0    -1.239375  0.749101 -0.528515
1    -1.036070  0.801436 -1.283712
2    -0.615579  1.579521 -1.391927
3     1.335978  1.348651  1.433564
4     0.658925  1.300019  0.571603
...        ...       ...       ...
2995 -0.455628  1.302303 -1.338027
2996 -0.434551  1.597813 -1.748643
2997  0.088277  1.638789 -2.193641
2998  1.525155  0.859234  1.505308
2999 -0.979817  0.563954 -1.539394

[3000 rows x 3 columns]>

In [4]:
x=df_x.values
y=df_y.values

In [5]:
#Normalizing Data
u = x.mean(axis=0)
sigma = x.std(axis=0)
x=(x-u)/sigma

In [6]:
print(x,y)

[[-0.93471307 -0.24439694 -0.46140414]
 [-0.7823013  -0.19327286 -1.08586573]
 [-0.46707053  0.56681072 -1.17534766]
 ...
 [ 0.06059095  0.62470809 -1.83827342]
 [ 1.13777964 -0.13681202  1.22033571]
 [-0.74013008 -0.42526137 -1.29728616]] [[1]
 [1]
 [1]
 ...
 [1]
 [0]
 [1]]


In [7]:
def hypothesis(x,w,b):
    hyp = np.dot(x,w)+b
    return sigmoid(hyp)
def sigmoid(z):
    return (1.0/(1.0+np.exp(-1.0*z)))
def error(x,w,b,y):
    m = x.shape[0]
    err=0
    for i in range(m):
        hyp = hypothesis(x,w,b)
        err += (y[i]*np.log2(hyp))+((1-y[i])*np.log2(1-hyp))
    return err/m
def grad(y,x,w,b):
    grad_w = np.zeros((w.shape))
    grad_b = 0.0
    for i in range(m):
        hyp = hypothesis(x[i],w,b)
        grad_w += (y[i]-hyp)*x[i]
        grad_b +=(y[i]-hyp)
    grad_b/=m
    grad_w/=m
    return [grad_w,grad_b]
def gradient_assent(x,y,w,b,learning_rate=0.1):
    m = x.shape[1]
    for j in range(100):
        for i in range(m):
            grad_w,grad_b=grad(y,x,w,b)
            w[i] = w[i]+learning_rate*grad_w[i]
            b = b+learning_rate*grad_b
    return w,b,error
        
def predict(x_query,w,b):
    confidence = hypothesis(x_query,w,b)
    if(confidence < 0.5):
        return 1
    else:
        return 0
def accuracy(x_query,y,w,b):
    y_pred=[]
    for i in range(y.shape[0]):
        y_pred.append(predict(x_query[i],w,b))
    y_pred=np.array(y_pred)
    return ((y_pred==y).sum())/y_pred.shape[0]
    
    
    
        
        

    
    

In [8]:
w = 2*np.random.random((x.shape[1],))
b = 2*np.random.random()

In [9]:
x_test = pd.read_csv("./Test/Logistic_X_Test.csv")
x_test=x_test.values
u = x_test.mean(axis=0)
sigma = x_test.std(axis=0)
x_test=(x_test-u)/sigma

In [10]:
y_test=[]
for i in range(x_test.shape[0]):
    y_test.append(predict(x_test[i],w,b))
y_test = np.array(y_test)
y_test.shape

(1000,)

In [11]:
x_test.shape

(1000, 3)

In [12]:
df = pd.DataFrame(y_test)

In [13]:
df.columns =["label"]

In [14]:
df.to_csv("Result.csv",index=False)